#!/usr/bin/env python3
"""Generate docs/call-chain.svg -- the one-directional call chain.

Purpose
    Visualize the project's core boundary: the page (yours) calls the voice
    module (yours), which calls the platform (someone else's service). The module
    is the caller, the platform is the callee, and the page never talks to the
    platform directly.

Dependencies
    Python 3.12+ standard library only (tomllib). No third-party packages.

Run
    python3 scripts/visualization/generate_call_chain.py
    (paths are resolved from __file__, so the working directory does not matter)

Output
    docs/call-chain.svg   (relative to the project root)

Dynamic values
    The version shown in the subtitle is read at run time from pyproject.toml.
"""

from __future__ import annotations

import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PYPROJECT = ROOT / "pyproject.toml"
OUT = ROOT / "docs" / "call-chain.svg"
FONT = "system-ui,-apple-system,'Segoe UI',Helvetica,Arial,sans-serif"

# (name, path-caption, role, colour, [extra lines])
NODES = [
    (
        "网页（你的）",
        "agent/deploy/voice-client.html",
        "收麦克风 · 放声音 · 显示状态",
        "#3b82f6",
        ["懂：麦克风 / 播放", "不懂：AI / 业务"],
    ),
    (
        "语音模块（你的）",
        "server/",
        "听与说 · 轮次 · 打断 · 填场",
        "#14b8a6",
        ["懂：VAD / STT / TTS / 延迟", "不懂：想什么"],
    ),
    (
        "平台（别人的服务）",
        "例如 Dify",
        "想什么 · 查什么 · 记什么",
        "#8b5cf6",
        ["懂：回答 / 工具 / 知识 / 记忆", "不是你的代码"],
    ),
]

ARROWS = ["WebSocket · 16k PCM", "HTTP + SSE"]


def read_version() -> str:
    with PYPROJECT.open("rb") as fh:
        return tomllib.load(fh)["project"]["version"]


def build_svg(version: str) -> str:
    w, h = 1200, 430
    cw, ch, cy = 300, 116, 140
    xs = [60, 450, 840]

    p: list[str] = []
    p.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
        f'viewBox="0 0 {w} {h}" font-family="{FONT}">'
    )
    p.append(
        "<defs>"
        '<linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">'
        '<stop offset="0" stop-color="#f8fafc"/><stop offset="1" stop-color="#eef2f7"/>'
        "</linearGradient>"
        '<marker id="arrow" markerWidth="11" markerHeight="11" refX="8" refY="3.5" orient="auto">'
        '<path d="M0,0 L8,3.5 L0,7 Z" fill="#64748b"/></marker>'
        '<filter id="soft" x="-20%" y="-20%" width="140%" height="140%">'
        '<feDropShadow dx="0" dy="3" stdDeviation="4" flood-color="#0f172a" flood-opacity="0.10"/>'
        "</filter>"
        "</defs>"
    )
    p.append(f'<rect width="{w}" height="{h}" fill="url(#bg)"/>')

    # header
    p.append(
        '<text x="60" y="48" font-size="24" font-weight="700" fill="#0f172a">'
        "调用链 · 方向只有一条</text>"
    )
    p.append(
        f'<text x="60" y="74" font-size="13" fill="#64748b">'
        f"v{version} · 模块是主动方，平台是被调用方；网页不知道平台的存在</text>"
    )

    # nodes
    for i, (name, caption, role, color, extras) in enumerate(NODES):
        x = xs[i]
        p.append(
            f'<g filter="url(#soft)">'
            f'<rect x="{x}" y="{cy}" width="{cw}" height="{ch}" rx="16" fill="#ffffff"/>'
            f"</g>"
        )
        p.append(f'<rect x="{x}" y="{cy}" width="{cw}" height="7" rx="3.5" fill="{color}"/>')
        p.append(
            f'<text x="{x + 24}" y="{cy + 44}" font-size="17" font-weight="800" '
            f'fill="{color}">{name}</text>'
        )
        p.append(
            f'<text x="{x + 24}" y="{cy + 68}" font-size="12" font-family="ui-monospace,monospace" '
            f'fill="#64748b">{caption}</text>'
        )
        p.append(
            f'<text x="{x + 24}" y="{cy + 92}" font-size="12.5" fill="#334155">{role}</text>'
        )
        for j, line in enumerate(extras):
            p.append(
                f'<text x="{x + 24}" y="{cy + ch + 24 + j * 20}" font-size="11.5" '
                f'fill="#8b97ab">· {line}</text>'
            )

    # arrows
    for i, label in enumerate(ARROWS):
        x1 = xs[i] + cw + 4
        x2 = xs[i + 1] - 6
        cyv = cy + ch / 2
        p.append(
            f'<line x1="{x1}" y1="{cyv}" x2="{x2}" y2="{cyv}" stroke="#64748b" '
            f'stroke-width="2.5" marker-end="url(#arrow)"/>'
        )
        mid = (x1 + x2) / 2
        p.append(
            f'<text x="{mid}" y="{cyv - 12}" text-anchor="middle" font-size="11.5" '
            f'font-weight="600" fill="#64748b">{label}</text>'
        )

    # footer note
    p.append(
        '<text x="60" y="380" font-size="12" fill="#64748b">'
        "自证：把平台停掉 → 网页照样开、模块照样在听照样出声，只是没人回答（它会明说「连不上」）。"
        "</text>"
    )
    p.append(
        '<text x="60" y="404" font-size="11" fill="#94a3b8">'
        "Generated by scripts/visualization/generate_call_chain.py "
        "— re-run it after changing the boundary."
        "</text>"
    )
    p.append("</svg>")
    return "".join(p)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build_svg(read_version()), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
