#
# Copyright (c) 2024-2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#
"""pipecat-quickstart - Pipecat voice agent.

Cascaded pipeline: Speech-to-Text -> LLM -> Text-to-Speech.

Generated by the official Pipecat CLI, with a small set of deliberate changes
(see README.md "changes vs. the official template").

Services used:
- Whisper / SenseVoice (Speech-to-Text)  local, no key
- OpenAI-compatible LLM (ModelScope / SenseNova / Suanli)  needs a key
- Piper (Text-to-Speech)  local, no key

Run:
    uv run bot.py

Logs (one run is enough to see the whole frontend+backend flow):
    logs/bot-<timestamp>.log   full DEBUG log of this run
    logs/bot-latest.log        fixed name, always points at the latest run
"""

import os

from dotenv import load_dotenv
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import LLMRunFrame
from pipecat.observers.error_observer import ErrorObserver
from pipecat.observers.loggers.metrics_log_observer import MetricsLogObserver
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMAssistantAggregatorParams,
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.runner.types import RunnerArguments
from pipecat.runner.utils import create_transport
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.workers.runner import WorkerRunner

from pipeline_logging import (
    ConversationLogger,
    install_client_logging,
    install_error_reporting,
    install_function_call_logging,
    log_boot_banner,
    resolve_log_paths,
    setup_logging,
)

# Log paths are computed once and reused; sinks are attached here first so that
# startup events are captured.
RUN_LOG, LATEST_LOG = resolve_log_paths("bot")
setup_logging(RUN_LOG, LATEST_LOG)

load_dotenv(override=True)

# ==========================================================================
# Configuration (all overridable via environment variables)
#
# Defaults all come from settings.py, which verify_stack.py also reads, so
# "the config the self-check reports" is exactly "the config the bot runs" --
# no drift between the two sides.
# ==========================================================================
import memory  # noqa: E402 - must come after load_dotenv
from guards import HallucinationGuard  # noqa: E402
from settings import (  # noqa: E402
    DEFAULT_OPENING_MESSAGE,
    DEFAULT_SYSTEM_INSTRUCTION,
    DEFAULT_VAD_STOP_SECS,
    VAD_STOP_SECS_OFFICIAL_DEFAULT,
    build_llm_extra,
    build_stt,
    build_summarization_config,
    build_tts,
    llm_config,
    stt_desc,
    stt_engine,
    thinking_disabled,
    tools_enabled,
    tts_desc,
    tts_engine,
)
from tools import build_tools  # noqa: E402 - same reason

# LLM provider (default modelscope; set LLM_PROVIDER=sensenova/suanli to switch).
# base_url / key / model are all resolved here, so switching is env-only.
LLM_CFG = llm_config()

# Disable "thinking" mode: reasoning models answer after a long reasoning pass,
# pushing the first token to 2-3 seconds. Each provider spells it differently,
# so what gets injected comes from the provider's thinking_body
# (ModelScope: enable_thinking / SenseNova: thinking={"type":"disabled"} / Suanli: none).
DISABLE_THINKING = thinking_disabled()

# Whether to expose function calling to the LLM.
# No frontend changes needed: pipecat reports calls and results as
# llm-function-call* messages to the prebuilt frontend.
ENABLE_TOOLS = tools_enabled()
# NOTE: the tool set is built per session inside run_bot, not here. Most tools are
# stateless, but set_reminder carries per-session state; building all schemas once at
# import time would turn that state into process-global state (see sample_tools.py).

# STT / TTS engine selection and construction live in settings.build_stt / build_tts,
# shared with verify_stack.py so the two sides cannot drift.

# VAD "end of speech" threshold. The official default of 0.2s splits a Chinese
# sentence at its comma pauses.
VAD_STOP_SECS = float(os.getenv("VAD_STOP_SECS", str(DEFAULT_VAD_STOP_SECS)))

SYSTEM_INSTRUCTION = os.getenv("SYSTEM_INSTRUCTION", DEFAULT_SYSTEM_INSTRUCTION)
OPENING_MESSAGE = os.getenv("OPENING_MESSAGE", DEFAULT_OPENING_MESSAGE)

VAD_STOP_SECS_DEFAULT = VAD_STOP_SECS_OFFICIAL_DEFAULT  # official value, for hints only

# ---------- Local persistence ----------
# The framework only offers in-memory short-term memory (LLMContext); long-term
# memory ships only as a mem0 adapter (cloud, needs a key), and there is no
# knowledge base or database at all -- so these have to be built here.
# SQLite has zero dependencies and can be swapped later.
memory.init_db()
memory.seed_demo_business()  # demo business data; overwritten once real ingestion runs


def _mask(value: str | None) -> str:
    if not value:
        return "not set [MISSING]"
    return f"set [OK] ({value[:6]}...{value[-4:]})"


def _pipecat_version() -> str:
    import pipecat

    return getattr(pipecat, "__version__", "?")


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session."""
    # Per-session id, NOT a module-level one: with more than one session in a process a
    # single shared id writes every session's turns under the same rows, so
    # ``recent_turns(session_id)`` reads someone else's conversation and the documented
    # "resume the previous session" promise breaks. Fall back to a fresh local id so the
    # recorder always has a stable value to write under.
    session_id = getattr(runner_args, "session_id", None) or memory.new_session_id()

    # Built here, not at import: set_reminder is stateful and must be bound to this session.
    tools = build_tools(session_id) if ENABLE_TOOLS else None

    # The pipecat runner calls logger.remove() on startup, so sinks must be
    # re-attached once the session starts, otherwise this session is never logged.
    setup_logging(RUN_LOG, LATEST_LOG)
    logger.info(f"[BOOT] --------- new session {session_id} ---------")

    recommended = LLM_CFG["recommended"]
    if recommended and LLM_CFG["model"] not in recommended:
        logger.warning(
            f"[BOOT] model {LLM_CFG['model']} is not among the {len(recommended)} "
            f"measured-recommended models; latency may be worse. recommended: {recommended}"
        )
    # ---------- Missing key must fail fast ----------
    # An earlier version only logged an ERROR and started anyway: the browser could
    # connect and the handshake succeeded, but the moment the user spoke there was
    # never an answer -- which looks like a network fault and is very hard to debug.
    # Here the session is aborted with actionable instructions.
    # Done before building STT/TTS so a missing key does not trigger model downloads.
    if not LLM_CFG["api_key"] and not os.getenv("ALLOW_MISSING_KEY"):
        raise RuntimeError(
            f"missing {LLM_CFG['api_key_env']}: LLM calls will certainly fail.\n"
            f"  1) open server/.env and set {LLM_CFG['api_key_env']} "
            f"(current provider LLM_PROVIDER={LLM_CFG['provider']}; "
            "make sure the key matches the provider)\n"
            "  2) restart: uv run bot.py\n"
            "  To debug only the frontend/transport, set ALLOW_MISSING_KEY=1 to skip this check."
        )

    log_boot_banner(
        {
            "Session ID": session_id,
            "Pipecat version": _pipecat_version(),
            "LLM provider": LLM_CFG["provider"],
            "LLM model": LLM_CFG["model"],
            "Disable thinking": DISABLE_THINKING,
            "Tools": (", ".join(t.name for t in tools.standard_tools) if tools else "disabled"),
            "Error to frontend": "on (ErrorObserver -> RTVI error)",
            "LLM key": _mask(LLM_CFG["api_key"]),
            "STT (configured)": stt_desc(stt_engine()),
            "TTS (configured)": tts_desc(tts_engine()),
            "VAD stop secs": f"{VAD_STOP_SECS}s (official {VAD_STOP_SECS_DEFAULT}s)",
            "System instruction": SYSTEM_INSTRUCTION,
            "Opening message": OPENING_MESSAGE,
            "This log": str(RUN_LOG),
        }
    )

    # ---------- Speech-to-Text / Text-to-Speech (local, no key) ----------
    # Built after the banner: construction loads local models (and downloads them on
    # the first run, which can take tens of seconds). It must not hide the config --
    # otherwise a cold-start download failure leaves you with no config output at all.
    # The engine actually in effect is logged separately: configuring sensevoice/kokoro
    # falls back when the dependency is missing.
    stt, stt_actual = build_stt()
    tts, tts_actual = build_tts()
    logger.info(f"[BOOT] STT in effect: {stt_actual}")
    logger.info(f"[BOOT] TTS in effect: {tts_actual}")

    # ---------- LLM (OpenAI compatible; default ModelScope, switchable) ----------
    llm_kwargs: dict = {
        "model": LLM_CFG["model"],
        "system_instruction": SYSTEM_INSTRUCTION,
    }
    # pipecat passes keys of OpenAILLMSettings.extra **directly as kwargs** to
    # client.chat.completions.create(...), so non-standard parameters must be wrapped
    # in the OpenAI SDK's extra_body to end up in the request JSON.
    # How to disable thinking differs per provider; that is what thinking_body is for.
    thinking_body = LLM_CFG["thinking_body"] if DISABLE_THINKING else None
    extra = build_llm_extra(thinking_body=thinking_body)
    if extra:
        llm_kwargs["extra"] = extra

    llm = OpenAILLMService(
        api_key=LLM_CFG["api_key"],
        base_url=LLM_CFG["base_url"],
        settings=OpenAILLMService.Settings(**llm_kwargs),
    )

    # ---------- Context and turn management ----------
    # FunctionSchemas carry their own handler and the LLM service registers them
    # automatically, so llm.register_function is not needed.
    context = LLMContext(tools=tools) if tools is not None else LLMContext()
    # Inject long-term memory into the context -- the model only "remembers" what it sees.
    memory.load_memory_into_context(context)
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
            vad_analyzer=SileroVADAnalyzer(params=VADParams(stop_secs=VAD_STOP_SECS))
        ),
        # Context summarization: the framework constructs the summarizer inside the
        # assistant aggregator and wires its events, so enabling it here is the whole
        # wiring. The summary is generated by the pipeline LLM through the normal frame
        # round-trip -- no separate client. See settings.build_summarization_config().
        assistant_params=LLMAssistantAggregatorParams(
            enable_auto_context_summarization=True,
            auto_context_summarization_config=build_summarization_config(),
        ),
    )

    # ---------- Pipeline ----------
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    # The error observer must be created first (it is a PipelineWorker constructor
    # argument); pushing errors to the frontend needs worker.rtvi, so the event
    # handler is attached after the worker exists.
    error_observer = ErrorObserver()

    # Trust guard: turns "claimed but never executed" into a visible alert (see guards.py).
    hallucination_guard = HallucinationGuard()

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(enable_metrics=True, enable_usage_metrics=True),
        # ConversationLogger: conversation timeline + per-turn stage latencies
        # MetricsLogObserver: per-service TTFB / TTFAT / TTFA
        # ErrorObserver: catches at the source, logs [ERROR] and pushes to the frontend
        # TurnRecorder: persists each turn. It must be an observer, not a pipeline
        #   processor -- text frames on both the user and assistant sides are consumed
        #   by their aggregators and not forwarded downstream (see memory.TurnRecorder).
        observers=[
            ConversationLogger(),
            MetricsLogObserver(),
            error_observer,
            # Function calls logged the way the framework recommends (its own observer).
            install_function_call_logging(),
            memory.TurnRecorder(session_id),
            # Trust guard: see guards.py
            hallucination_guard,
        ],
    )
    install_error_reporting(worker, error_observer)

    # Trust guard **enforcement**: after a false claim is detected, inject a correction
    # instruction and let the model answer again honestly.
    # Each action is corrected at most once, to avoid a
    # "correct -> claim again -> correct again" loop.
    corrected: set[str] = set()

    async def _correct_false_claim(label: str, executed: list[str]) -> None:
        if label in corrected:
            logger.warning(f"[GUARD] '{label}' already corrected; skipping to avoid a loop")
            return
        corrected.add(label)
        context.add_message(
            {
                "role": "user",
                "content": (
                    f"系统检测到：你刚才声称「{label}」，但并没有对应工具的成功调用记录。"
                    "请如实告诉用户你尚未完成，不要继续声称已完成。"
                ),
            }
        )
        await worker.queue_frames([LLMRunFrame()])

    hallucination_guard.set_on_violation(_correct_false_claim)

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)
    await runner.add_workers(worker)

    # Frontend (browser) event logging: connect, disconnect, RTVI messages, client info.
    install_client_logging(transport, worker.rtvi)

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        logger.info("[BOOT] frontend ready; triggering the opening message")
        # The role must be "user", not "developer"/"system":
        #   1) ModelScope's OpenAI-compatible endpoint rejects the "developer" role with
        #      a 400 "Unexpected message role", and it stays in the context so every
        #      later turn fails too;
        #   2) that endpoint also requires **at least one user message**, otherwise it
        #      returns 400 "No user query found in messages.", so a system-role message
        #      cannot be sent either.
        context.add_message({"role": "user", "content": OPENING_MESSAGE})
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("[CLIENT] session ended; cleaning up resources")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }
    transport = await create_transport(runner_args, transport_params)
    await run_bot(transport, runner_args)


if __name__ == "__main__":
    logger.info(f"[BOOT] process starting | log: {RUN_LOG}")
    logger.info(f"[BOOT] fixed-name log: {LATEST_LOG} (always points at the latest run)")

    from pipecat.runner.run import main

    main()
